### ISSUE TITLE
User jinja2 for HTML templates instead of manually creating them

### ISSUE THREAD

**Issue by mikofski** [sandialabs/pecos#14]
Current use of strings to build HTML is fragile and redundant in some cases. Use of existing mature robust HTML python templates will make management development and collaboration easier.

I recommend jinja2
http://jinja.pocoo.org/
https://pypi.python.org/pypi/Jinja2
https://github.com/pallets/jinja

In a nutshell HTML templates are rendered by jinja2 which replaces jinja2 markup with desired content. Jinja2 markup is embedded directly in the HTML and is a modified subset of python. Python variables are passed to the Jinja2 renderer along with the template and expanded in the output according to the mark-up in the template. Base templates can be "included" to remove redundant content from multiple pages, such as headers and footers, scripts and CSS.

**Comment by kaklise** [comment]
#15 merged
