### ISSUE TITLE
examples: jinja2.exceptions.TemplateNotFound: monitoring_report.html

### ISSUE THREAD

**Issue by dacoex** [sandialabs/pecos#20]
Example misses some templates:

```
(pecos_trial) C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\envs\pecos_trial\pecos\examples\pv>python pv_example.py
Reading Campbell Scientific CSV file Baseline6kW_2015_11_11.dat
INFO:pecos.io:Reading Campbell Scientific CSV file Baseline6kW_2015_11_11.dat
Reading Campbell Scientific CSV file MET_2015_11_11.dat
INFO:pecos.io:Reading Campbell Scientific CSV file MET_2015_11_11.dat
Check timestamp

[...]

INFO:pecos.io:Writing test results csv file Results\Baseline_System_test_results.csv
Writing HTML report
INFO:pecos.io:Writing HTML report
Traceback (most recent call last):
  File "pv_example.py", line 128, in <module>
    'Baseline System, Performance Monitoring Report', config)
  File "C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\envs\pecos_trial\lib\site-packages\pecos-0.1.2-py3.5.egg\pecos\io.py", line 240, in write_monitoring_report
    html_string = _html_template_monitoring_report(content, title, logo, encode)
  File "C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\envs\pecos_trial\lib\site-packages\pecos-0.1.2-py3.5.egg\pecos\io.py", line 337, in _html_template_monitoring_report
    template = env.get_template('monitoring_report.html')
  File "C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\envs\pecos_trial\lib\site-packages\jinja2\environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\envs\pecos_trial\lib\site-packages\jinja2\environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\envs\pecos_trial\lib\site-packages\jinja2\loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: monitoring_report.html

(pecos_trial) C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\envs\pecos_trial\pecos\examples\pv>
```

**Comment by kaklise** [comment]
Thanks for the comment.  monitoring_report.html is in pecos/templates and the following line in io.py should define how jinja finds that template.
env = Environment(loader=PackageLoader('pecos', 'templates'))
Can you let me know if you have the file pecos/templates/monitoring_report.html?  And I'll look into this further.

**Comment by wholmgren** [comment]
Might need to be added to the manifest file.

**Comment by kaklise** [comment]
Good idea.  I'll try that.  Thanks.

**Comment by dacoex** [comment]
I have the file which came as part of the clone.

I tried 1 time running from inside the cloned folder and also outside.

Maybe best to have a sequence of standard locations, like:
1) site-package/pecos 
2) the directory where the current script is located 
3) location definition defined in the config.yaml

**Comment by kaklise** [comment]
I'm not able to replicate this error.  In the simplest case, you should be able to run (from any location)

import pecos
pecos.logger.initialize()
pm = pecos.monitoring.PerformanceMonitoring()
pecos.io.write_monitoring_report('test.html', pm)

The pv_example does have to be run in the pecos/examples/pv folder to be able to find the config.yml and data files.  The user can specify a path to those files if they are located somewhere else.

**Comment by dacoex** [comment]
I confirm that it works.

I was using a conda env. I assume that the previous environment was not well set-up.

---> maybe the environment before was not well created and thus missing a dependency?

Here the steps requird to set the thing up for running the example:

```
conda create -n pecos_test anaconda
activate pecos_test
git clone https://github.com/sandialabs/pecos pecos_upstream

cd pecos_upstream
pip install .
cd examples\pv
conda install -c pvlib pvlib

python pv_example.py
```

Maybe this could be added to the docs.

**Comment by kaklise** [comment]
I glad to hear that it works.  I'm not familiar with conda environments, but I am interested in learning.  Once I get up to speed on that, I'll add some instructions to the docs.

**Comment by dacoex** [comment]
> I'm not familiar with conda environments, but I am interested in learning. Once I get up to speed on that, >I'll add some instructions to the docs.
Honestly, conda guys need to improve the their docs on the topic of managing environments.
Too many faqs / blogs are out there to explain the simple procedure. 
But yes, above part could be added. Or better one may use a kapsel:
[Automate your README: conda kapsel Beta 1 | Continuum](https://www.continuum.io/blog/developer-blog/automate-your-readme-conda-kapsel-beta-1)

Now in the next weeks I will explore the combo pecis + pvlib more. The workflow seems to be programmed well. 
After advancing I may have further feedback.
