### ISSUE TITLE
Contract reference  value as benchmark 

### ISSUE THREAD

**Issue by dacoex** [sandialabs/pecos#24]
I just read the presentation at
https://pvpmc.sandia.gov/download/5289/

Questions:

1) for what type of system is pecos currently developed?
2) in commercial settings, a contractual reference value, e.g. guaranteed PR, guaranteed yield factor, guaranteed availability are used as benchmark to check if systems perform as expected and O&M contractor complies with obligations. Are you planning to add such functionality?

As example, we could generate expected values based on a TMY input and a simple system modelled with pvlib. Then, the performance is validated against that value.

**Comment by kaklise** [comment]
The software is general and can be applied to a wide range of systems.  Pecos includes the basic functionality to run the analysis you describe in 2.  The are some PV performance metrics included in Pecos and we can add more.  Computing expected values using TMY and pvlib would be a good demonstration of this capability.  Let's plan a time to talk about your application.  Send me an email at kaklise@sandia.gov
