### ISSUE TITLE
jinja2 and pandas requirements

### ISSUE THREAD

**Issue by wholmgren** [sandialabs/pecos#36]
Two requirements issues:
1. pecos needs jinja2 but it's not included in the 'install_requires' list. 
2. Is the pandas >= 0.18 requirement actually necessary for pecos? I have a mess of code that's tied to 0.17. I ran the pecos test suite using pandas 0.17 and it didn't error, so I'm wondering if there are any other known issues.

Thanks!

**Comment by kaklise** [comment]
Closed, PR #40
