### ISSUE TITLE
compatibility with pvlib 0.4

### ISSUE THREAD

**Issue by wholmgren** [sandialabs/pecos#38]
I see that `pecos.pv.basic_pvlib_performance_model` uses older function signatures for pvlib's `sapm` and `singlediode`. It would be straightforward to update these for pvlib's 0.4 api change, possibly with a version check to retain compatibility. However, it seems to me that pvlib 0.4's ModelChain already accomplishes what this function sets out to do and maybe the function can be deprecated? I ran into the issue when trying to run the `pv_example.py` script. 

On a related note, I love the yaml files in the pecos examples and I would like to see pvlib gain the ability to make a `Location` and `PVSystem` from a yaml file. That might make it slightly easier to integrate the pvlib changes into the `pv_example.py` script.

**Comment by kaklise** [comment]
I wrote the pecos.pv.basic_pvlib_performance_model before pvlib had ModelChain, so this function can be replaced with a direct call to pvlib.  Adding a version test to make sure that pecos and pvlib are compatible would be great.  As we build up more examples that integrate pvlib, this will be very important.  It should be pretty easy to build a Location and PVSystem object from yaml.  I'll try to work these updates to the pv_example soon.

**Comment by kaklise** [comment]
Closed, PR #40
