### ISSUE TITLE
check_timestamp with irregular time stamps

### ISSUE THREAD

**Issue by wholmgren** [sandialabs/pecos#39]
Some data logging systems record data at irregular time stamps. It would be helpful to me if `check_timestamp` could handle this case. I'm not sure what the best way to implement it would be. Maybe something like this?

``` python
In [36]: index = pd.DatetimeIndex([pd.Timestamp('20161017 00:05:00'), pd.Timestamp('20161017 02:03:00'), pd.Timestamp('20161017 02:50:00')])

In [37]: s = pd.Series([0, 2, 3], index=index)

In [43]: s.resample('3600s').count() == 0
Out[43]:
2016-10-17 00:00:00    False
2016-10-17 01:00:00     True
2016-10-17 02:00:00    False
Freq: 3600S, dtype: bool
```

**Comment by wholmgren** [comment]
On a related note, the doc string should be updated to "Check time series for **missing**, non-monotonic and duplicate timestamps."

**Comment by kaklise** [comment]
It's important that the index is sampled at the expected frequency and some data loggers have slight (or large) offsets that make this troublesome.  For example, you might want to adjust a timestamp that records at 00:01:01 to 00:01:00.  You can use the resample method, as you have shown, or you can use a rounding method that I added to pecos.utils to round the index up, down, or to the nearest specified frequency.  This is particularly important if you are merging multiple dataframes in a single pecos analysis.  If the timestamps are slightly off, they will not merge as expected.  This is the main reason I decided to keep this adjustment outside check_timestamp function.  Also, there are many ways a user might want to clean up a timestamp before adding the data to pecos, and I wasn't sure which methods to support.   I'm open to ideas!  If anyone has a use case for this issue, that would be great.

**Comment by wholmgren** [comment]
My use case is that I have randomly timestamped data from a dozen PV plants. I can resample the data to hourly resolution if I want uniform timestamps, but this resampling can hide some problems with the raw data. For example, a single data point that is out of range could be flagged with an instantaneous analysis, but the mean of 4 data points within an hour might be within range. So, I'd like ``check_timestamp`` to make sure that there's a data point every 15 minutes and I'd like ``check_range`` to make sure that the raw data points are all within range. I mostly do plant by plant analysis to avoid the merging problems you mentioned.

I tried to add a ``check_exact_times`` option to ``check_timestamp`` and couldn't make the reporting work the way I wanted it to:

https://github.com/wholmgren/pecos/blob/flexiblemissing/pecos/monitoring.py#L280

https://travis-ci.org/wholmgren/pecos/jobs/168688701

I think I'd have to spend some time to really understand the mask/append_test_results logic before I can make this work, but I'm not sure if it's in the scope of pecos or not.

**Comment by kaklise** [comment]
Sorry for the delay on this.   In the example that you created, is it important to record that you have two entries in the 2:00 hour? or do you just want to record that you are missing an entry in the 1:00 hour?

**Comment by cedricleroy** [comment]
+1 for @wholmgren request. I have the exact same use case where we want to clean raw data (what you call data with irregular time stamps), before to aggregate them. Working on data already aggregated is biaised as it mixes good and bad data. Is there any plan for that?

**Comment by kaklise** [comment]
We can support that.  If you could provide some hypothetical input and desired output, that would be great.  I'll review @wholmgren request again.
