### ISSUE TITLE
Unable to install pecos via pip

### ISSUE THREAD

**Issue by rivers31334** [sandialabs/pecos#49]
I am unable to install picos via the pip command. Is this a known problem regarding the ReadMe file?  Can anyone offer any advice specifically via the pip command?

![image](https://user-images.githubusercontent.com/28614282/29185771-5486b40e-7dd8-11e7-87be-10a0f59cf326.png)

**Comment by kaklise** [comment]
I was not able to replicate the error, but I think I found a solution based on similar issues posted online.  I added the readme and license files to the manifest.  I will check in this change today, and update the pip distribution.

**Comment by rivers31334** [comment]
I appreciate you.  A bit newish still to the world of python, and very
grateful to have resources to come to.  I will give it a try.

**Comment by kaklise** [comment]
Thanks for pointing out this issue.  I won't be able to post the new pip distribution until later this afternoon 
(version 0.1.6).  Once that's posted, let me know if you run into any issues.

**Comment by rivers31334** [comment]
It worked like a charm. Thank you, Katherine.
