### ISSUE TITLE
use pandas 0.24 has bug

### ISSUE THREAD

**Issue by poposhi** [sandialabs/pecos#56]
i use original code "simple_example.py" ,original file "simple.xlsx" in example.
environment in pandas 0.24
system show:
TypeError: Invalid comparison between dtype=float64 and Timedelta

i change pandas to 0.23
it's solved.

For people who have encountered the same mistake

**Comment by kaklise** [comment]
Thanks, I'll look into it and see if there is a simple solution in Pecos to avoid the conflict

**Comment by poposhi** [comment]
thanks. this my first time to dis discuss an issue on internet. Unfamiliar with culture. 
If you need more detailed information, I can attach it.
