### ISSUE TITLE
Example of check_timestamp

### ISSUE THREAD

**Issue by UGuntupalli** [sandialabs/pecos#64]
@kaklise : 
             Katherine, Hope you are doing well. Can you kindly post an example for how to use the check_timestamp function. Here is what I tried : 

```python 
import pandas as pd
from random import random
from pecos import monitoring

# Build a random data set
ts_index = pd.date_range('1/1/2000', periods=1000, freq='T')
v1 = [random() for i in range(1000)]
v2 = [random() for i in range(1000)]
v3 = [random() for i in range(1000)]
ts_df = pd.DataFrame({'v1':v1,'v2':v2,'v3':v3},index=ts_index)

# Test for timestamps  
t = monitoring.check_timestamp(
    data=ts_df,
    frequency=3600
)
print(t["mask"])
```
   Since the index is the time-series for the entire data frame: 

1. Shouldn't the result just have one column indicating True or False ? 
2. Reading through the documentation, the function should test for: 

- monotonicity (since I am using the default, it should reindex) 
- missing (should fill in any missing timestamps) 
- duplicates (drop any duplicates, by retaining the first occurrence) 

  After performing these actions, I am not sure how to interpret the booleans that it returns which are the size of the data frame. Could you kindly provide an example clarifying this ?

**Comment by UGuntupalli** [comment]
bump ....

**Comment by kaklise** [comment]
Thanks for providing the example.  The mask includes a boolean value for each entry in the dataframe (for each index and column).  For the timestamp test, the value (T/F) will be the same across all columns.  While the timestamp test could simply return a value for each index, the way it is coded now keeps the mask a consistent size for other tests.  In the example, the original data is sampled per minute.  Since the timestamp test checks for hourly data (frequency=3600) and is looking for an exact match (exact_times=True), the resulting data is resampled to that frequency and the mask includes True for each entry.

**Comment by UGuntupalli** [comment]
@kaklise, 
           So is it fair to say that the output of a timestamp test should always be the same across multiple columns ? This is what I was expecting, however, for an example I am analyzing, the results are not the same across the columns of the data frame which is perplexing. To illustrate further, please consider the following example, where I have evenly spaced hourly data frame with 4 columns and 5 rows. Column 2 and Column 3 has missing data, but that in _my humble opinion should be immaterial_ to the functioning of check_timestamp. 
          However, when I look at the mask i.e. the booleans generated by the check_timestamp function, they are not uniform across the columns, instead they vary, please refer to the screenshot below. Since the data is sampled correctly, shouldn't the mask generated indicated across all the columns have the same value  ? Could you kindly help clarify ? 

```python 
   import pandas as pd
   import numpy as np
   from pecos import monitoring

   # Create a random data frame
   df = pd.DataFrame(data=[["2015-01-01 00:00:00", -0.76, np.nan, np.nan, 1.2],
                        ["2015-01-01 01:00:00", -0.73, np.nan, np.nan, 1.1],
                        ["2015-01-01 02:00:00", -0.71, np.nan, np.nan, 1.1],
                        ["2015-01-01 03:00:00", -0.68, np.nan, np.nan, 1.1],
                        ["2015-01-01 04:00:00", -0.65, np.nan, np.nan, 1.0]],
                  columns=['DateTime', 'column1', 'column2', 'column3', 'column4'])

   # Set the index
   df["DateTime"] = pd.to_datetime(df["DateTime"])
   df.set_index("DateTime", inplace=True)

   # Run timestamp flag
   timestamp_flag_check = monitoring.check_timestamp(
      data=df,
      frequency=3600
   )

   print(timestamp_flag_check['mask'])

   
```
<img width="357" alt="pycharm64_YE2v133aHw" src="https://user-images.githubusercontent.com/47903157/88463173-c3c97500-ce65-11ea-9e14-244df2a871b7.png">

**Comment by kaklise** [comment]
Thanks, I found the issue.  When the mask is created, it assumes that Null values should be defined as False.  As you point out, this is not inline with the timestamp test.  This would be identified in the missing values test.  I'll fix this an push an update.
