### ISSUE TITLE
TimeStamps on Console output

### ISSUE THREAD

**Issue by MarcBarlett** [sandialabs/pecos#68]
I would be interested in seeing a timestamp along with the console output while this runs.
Related to this when I run the PECOS program there appears to be a longer delay in creating the custom.png images over the test_result.png images.  is this normal?

![image](https://user-images.githubusercontent.com/58749850/105243195-f4941980-5b2b-11eb-94f0-310341ac75ef.png)
![image](https://user-images.githubusercontent.com/58749850/105244102-425d5180-5b2d-11eb-8ba7-a65bb103f96d.png)

**Comment by kaklise** [comment]
Thanks for the suggestion.  I can add a timestamp to the console output.  I'm not sure about the delay when creating the custom images, are you running the PV example?

**Comment by MarcBarlett** [comment]
I am running the simple_example_using_config,py
________________________________

**Comment by kaklise** [comment]
I don't see much of a delay when creating graphics from simple example.

**Comment by kaklise** [comment]
A timestamp has been added to the logger.
