### ISSUE TITLE
check_timestamp failed due to deprecation of 'is_monotonic'

### ISSUE THREAD

**Issue by kchong75** [sandialabs/pecos#76]
'is_monotonic' is deprecated since Pandas 1.5.0

**Comment by kaklise** [comment]
Thanks for pointing this out, I'll update the code to avoid this depreciation.

**Comment by kaklise** [comment]
@ssolson Yes! Thanks for the reminder.

**Comment by kaklise** [comment]
@ssolson, version 0.3.0 is now available on pypi
