### ISSUE TITLE
matplotlib doesn't support jpg on macosx

### ISSUE THREAD

**Issue by jforbess** [sandialabs/pecos#8]
The example files all use jpg output files, but there is apparently a bug in matplotlib handling of jpg on macosx. Can I change output files to png to make the examples run on every platform? Is this something Travis CI should catch if there were plots in the test files?

**Comment by kaklise** [comment]
good catch.  I had not created tests for graphics yet, so I had not seen that issue.  This should be an easy fix.  I'll add an 'image_format' parameter to the 'plot_test_results' function and set the default to 'png'.  I can do that now.
